### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/~/BCNet/code/module/../../smpl_pytorch/model/neutral_smpl_with_cocoplus_reg.txt'

### ISSUE THREAD

**Issue by asimniazi63** [jby1993/BCNet#1]
Traceback (most recent call last):
  File "infer.py", line 115, in <module>
    net=M.ImageReconstructModel(skinWsNet,True)
  File "/home/asimniazi63/Desktop/BCNet/code/module/ImageReconstructModel.py", line 426, in __init__
    self.smpl=SMPL(osp.join(osp.dirname(__file__),'../../smpl_pytorch/model/neutral_smpl_with_cocoplus_reg.txt'),obj_saveable=True)
  File "../smpl_pytorch/SMPL.py", line 18, in __init__
    with open(model_path, 'r') as reader:
FileNotFoundError: [Errno 2] No such file or directory: '/home/asimniazi63/Desktop/BCNet/code/module/../../smpl_pytorch/model/neutral_smpl_with_cocoplus_reg.txt'

**Comment by asimniazi63** [comment]
solved: link available in smpl_pytorch folder
